<a href="https://colab.research.google.com/github/san031/Machine_learning-Artificial-Intelligence-Projects/blob/main/machine_learning/isolationforest/Isolation_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/sample_data/tr_server_data.csv",header = None, names = ["feature_1","feature_2"])

In [ ]:
df.head()

   feature_1  feature_2
0     13.047     14.741
1     13.409     13.763
2     14.196     15.853
3     14.915     16.174
4     13.577     14.043

In [ ]:
df.shape

(307, 2)

In [ ]:
df.describe()

        feature_1   feature_2
count  307.000000  307.000000
mean    14.112253   14.997675
std      1.355974    1.309696
min      4.752600    4.126200
25%     13.403500   14.362000
50%     14.060000   15.023000
75%     14.675500   15.654500
max     23.340000   24.350000

In [ ]:
df.isnull().sum()

feature_1    0
feature_2    0
dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
X_scaled = scaler.fit_transform(df)

### train model using isolation forest

In [ ]:
from sklearn.ensemble import IsolationForest

In [ ]:
model = IsolationForest(
    n_estimators=200,
    contamination=0.05,
    random_state=42
)

In [ ]:
model.fit(X_scaled)

IsolationForest(contamination=0.05, n_estimators=200, random_state=42)

### detect anamolies

In [ ]:
## prediction
## -1 = anamoly, 1 = normal

In [ ]:
df["anamoly"] = model.predict(X_scaled)

In [ ]:
df.head()

   feature_1  feature_2  anamoly
0     13.047     14.741        1
1     13.409     13.763        1
2     14.196     15.853        1
3     14.915     16.174        1
4     13.577     14.043        1